import { useState } from "react";
import InstitutionLayout from "../layout/institutitondashboardlayout";
import API_URL from "../config/api.js";
import { useNavigate } from 'react-router-dom';
import axios from "axios";

export default function CreateTeacher() {
  const navigate = useNavigate();

  const institutionCode = localStorage.getItem("institutionCode");
  const branch = localStorage.getItem("branch");

  const [form, setForm] = useState({
    teacherName: "",
    email: "",
    mobile: "",
    gender: "",
    subjects: ""
  });

  const handleChange = (e) => {
    setForm((prev) => ({
      ...prev,
      [e.target.name]: e.target.value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (
      !form.teacherName.trim() ||
      !form.email.trim() ||
      !form.mobile.trim() ||
      !form.gender.trim() ||
      !form.subjects.trim()
    ) {
      alert("All fields are required");
      return;
    }

    try {
      await axios.post(
        `${API_URL}/api/teachers/create`,
        {
          ...form,
          subjects: form.subjects.split(",").map((s) => s.trim()),
          institutionCode,
          branch: branch === "null" ? null : branch
        },
        { withCredentials: true }
      );

      alert(`Teacher Created`);
      navigate("/institution/dashboard");

    } catch (error) {
      alert(error.response?.data?.message || "Error creating institution");
      console.log(error);
    }
  };

  return (
    <InstitutionLayout title="Add Teacher">
      <div className='min-h-[80vh] flex justify-center items-center'>
        <div className="w-full max-w-md bg-white rounded-2xl shadow-2xl p-6">

          <h1 className="text-2xl font-bold mb-6 text-[#1fa2a6]">Vidayanta</h1>

          <form onSubmit={handleSubmit}>
            <label htmlFor="form.teacherName"className='block font-normal mb-1'>Teacher Name</label>
            <input
              name="teacherName"
              placeholder="Teacher Name"
              className='w-full border rounded-lg px-2 py-1 mb-2'
              value={form.teacherName}
              onChange={handleChange}
            />
            <label htmlFor="form.email"className='block font-normal mb-1'>Email</label>
            <input
              name="email"
              type="email"
              placeholder="Email"
              className='w-full border rounded-lg px-2 py-1 mb-2'
              value={form.email}
              onChange={handleChange}
            />
            <label htmlFor="form.mobile"className='block font-normal mb-1'>Mobile</label>
            <input
              name="mobile"
              type="number"
              placeholder="Mobile"
              className='w-full border rounded-lg px-2 py-1 mb-2'
              value={form.mobile}
              onChange={handleChange}
            />
            <label htmlFor="form.gender"className='block font-normal mb-1'>Gender</label>
            <input
              name="gender"
              placeholder="Gender"
              className='w-full border rounded-lg px-2 py-1 mb-2'
              value={form.gender}
              onChange={handleChange}
            />
            <label htmlFor="form.subjects"className='block font-normal mb-1'>Subjects</label>
            <input
              name="subjects"
              placeholder="Subjects (comma separated)"
              className='w-full border rounded-lg px-2 py-1 mb-2'
              value={form.subjects}
              onChange={handleChange}
            />

            <button className="w-full bg-[#1fa2a6] text-white py-3 rounded-lg">
              Create Teacher
            </button>

            <p className='w-full text-[#1fa2a6] flex justify-center items-center'>
              Credentials will be automatically generated by the system
            </p>

          </form>
        </div>
      </div>
    </InstitutionLayout>
  );
}