import { useState } from 'react';
// import API from '../config/api';
import { useNavigate } from 'react-router-dom';
import Superadminlayout from '../layout/superadmindashboardlayout';
import axios from 'axios';

function CreateInstitution() {
  const navigate = useNavigate()
  const [institutionName , setInstitutionName] = useState("");
  const [branch , setBranch] = useState("");
  const [email , setEmail] = useState("");
  const [mobile , setMobile] = useState("");
  const [address , setAddress] = useState("");

  const handleSubmit = async (e) => {
  e.preventDefault();
   
  try {
    if(!email){
      alert("Email is required");
      return;
    }
    const res = await axios.post(
      "http://localhost:5000/api/superadmin/create-institution",
      {
        institutionName,
        branch,
        email,
        mobile,
        address
      },
      { withCredentials: true }
    );
    console.log(res);
    // console.log(res);
    alert(
      `Institution Created`

    );
    navigate("/superadmin/dashboard")
     } catch (error) {
    console.log(error.response?.data?.message || "Error creating institution");
  }
  };
  return (
    <Superadminlayout>
    <div className='h-screen w-full bg-gradient-to-br from-[#ffffff] via-[#f5faff] to-[#dbf4f5] flex justify-center items-center'>
      <div className='w-[75%] h-[92vh] bg-white rounded-2xl shadow-2xl flex overflow-hidden '>
        <div className='hidden lg:block w-[40%]'>
          <img 
          src="/images/institutioncreation.jpeg"
          alt='institution'
          className='w-full h-full object-fill'/>
        </div>
        <div className='w-full lg:w-[60%] p-4 bg-gray-200 overflow-y-auto'>
          <div className='block lg:hidden text-3xl font-bold text-[#1fa2a6] mb-0.5'>
            Vidayanta
          </div>
          <h2 className='text-2xl font-semibold text-[#1fa2a6] mb-2'>
            Create Institution
          </h2>
          <form onSubmit={handleSubmit}>
          {/* <form> */}
          {/* <div> */}
            {/* Institution name */}
            <div className='mb-2'>
              <label htmlFor="Institution name"className='block font-normal mb-1'>
                Institution Name
              </label>
              <input 
              type='text'placeholder='Enter Institution name'
              className='w-full border rounded-lg px-2 py-1 focus:outline-2 focus:outline-[#1fa2a6]'
              value={institutionName}
              onChange={(e)=>setInstitutionName(e.target.value)}/>
            </div>
            {/* branch */}
            <div className='mb-2'>
              <label htmlFor="branch"className='block font-normal mb-1'>
                Branch Number
              </label>
              <input 
              type='number'placeholder='Enter branch number'
              className='w-full border rounded-lg px-2 py-1 focus:outline-2 focus:outline-[#1fa2a6]'
              value={branch}
              onChange={(e)=>setBranch(Number(e.target.value))}/>
            </div>
            {/*email */}
            <div className='mb-2'>
              <label htmlFor="email"className='block font-normal mb-1'>
                Email
              </label>
              <input 
              type='email' placeholder='Enter Email'
              className='w-full border rounded-lg px-2 py-1 focus:outline-2 focus:outline-[#1fa2a6]'
              value={email}
              onChange={(e)=>setEmail(e.target.value)}/>
            </div>
            {/* mobile */}
            <div className='mb-2'>
              <label htmlFor="mobile"className='block font-normal mb-1'>
                Mobile Number
              </label>
              <input 
              type='number'placeholder='Enter Mobile Number'
              className='w-full border rounded-lg px-2 py-1 focus:outline-2 focus:outline-[#1fa2a6]'
              value={mobile}
              onChange={(e)=>setMobile(e.target.value)}/>
            </div>
            {/* address  */}
            <div className='mb-2'>
              <label htmlFor="address"className='block font-normal mb-1'>
                Address
              </label>
              <textarea
              type='text'placeholder='Enter Address'
              className='w-full border rounded-lg px-2 py-1 focus:outline-2 focus:outline-[#1fa2a6]'
              value={address}
              onChange={(e)=>setAddress(e.target.value)}/>
            </div>
            {/*submit button  */}
            <button type='submit' 
            // onClick={handleSubmit}
            className='w-full bg-[#1fa2a6] text-white font-bold  py-3 rounded-lg hover:bg-[#0f7c8f]'>
              Create Institution
            </button>
            <p className='w-full text-[#1fa2a6] flex justify-center items-center'>Credentials will be automatically generated by the system</p>
            {/* </div> */}
          </form>
        </div>
      </div>
    </div>
    </Superadminlayout>
  )
}

export default CreateInstitution;